version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"

    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"

    - package-ecosystem: "composer"
      directory: "/tools/cs-fixer"
      schedule:
          interval: "weekly"
      ignore:
          - dependency-name: "friendsofphp/php-cs-fixer"

    - package-ecosystem: "composer"
      directory: "/tools/infection"
      schedule:
          interval: "weekly"

    - package-ecosystem: "composer"
      directory: "/tools/monorepo"
      schedule:
          interval: "weekly"

    - package-ecosystem: "composer"
      directory: "/tools/phpbench"
      schedule:
          interval: "weekly"

    - package-ecosystem: "composer"
      directory: "/tools/phpstan"
      schedule:
          interval: "weekly"

    - package-ecosystem: "composer"
      directory: "/tools/phpunit"
      schedule:
          interval: "weekly"
