name: "Test Suite"

on:
  pull_request:
  push:
    branches:
      - "1.x"
  schedule:
    - cron:  '0 8 * * *'

jobs:
  tests:
    name: "Tests"
    uses: aeon-php/actions/.github/workflows/composer-script-test.yaml@main

  static-analyze:
    name: "Static Analyze"
    uses: aeon-php/actions/.github/workflows/composer-script-static-analyze.yaml@main
